### PR TITLE
#21-Sidebar-john-john

### PR DESCRIPTION
**Pull request by Johng117**
## Naming Rules
Name your PR like this: ISSUENUMBER-TITLE-YOURNAME

## Description
Created a responsive sidebar.

## Related to
Make sure you include the issue number with a hash sign # so Github can link this PR to the right issue, like this:

Fixes #1

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have carefully reviewed my own code
- [x] I have commented my code
- [x] I have updated any documentation

### CODE REVIEW

**Review by ChidimmaOfodum — CHANGES_REQUESTED** [review]
Please update this branch so that it has the latest changes from the dev branch. The web pack config files and some server files are also coming up in the changes history too

**Comment by Johng117** [comment]
> Please update this branch so that it has the latest changes from the dev branch. The web pack config files and some server files are also coming up in the changes history too

I am not sure what you mean, merge dev into this branch?

**Comment by ChidimmaOfodum** [comment]
> > Please update this branch so that it has the latest changes from the dev branch. The web pack config files and some server files are also coming up in the changes history too
> 
> I am not sure what you mean, merge dev into this branch?

Pull latest changes from dev, rebase with your branch and resolve conflicts along the way.

**Comment by Johng117** [comment]
> > > Please update this branch so that it has the latest changes from the dev branch. The web pack config files and some server files are also coming up in the changes history too
> > 
> > 
> > I am not sure what you mean, merge dev into this branch?
> 
> Pull latest changes from dev, rebase with your branch and resolve conflicts along the way.

ok will do

**Review by ChidimmaOfodum — APPROVED** [review]

**Review by kavitappatil — APPROVED** [review]
LGTM, thanks

**Pull request merged**
